# Generated by Django 5.0 on 2024-01-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='celphone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
